name: ja
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  google_fonts: ^4.0.3
  fluttertoast: ^8.2.2
  device_info_plus: any
  get_storage: ^2.1.1
  firebase_messaging: ^14.6.8
  flutter_background_service: ^5.0.1
  contacts_service: ^0.6.3
  permission_handler: ^11.0.0
  flutter_otp_text_field: ^1.1.1
  flutter_local_notifications: ^15.1.1
  shared_preferences: ^2.2.1
  flutter_background_service_android: ^6.0.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  sms_sender:
    path: /Users/prathamsarankar/Desktop/Plugins/sms_sender
#  sms_sender:
#    path: /Users/prathamsarankar/AndroidStudioProjects/sms_sender

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
